version: 0.2

phases:
  install:
    commands:
      - curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
      - apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
      - apt-get update && sudo apt-get install terraform
  build:
    commands:
      - cd dev
      - terraform init
      - terraform plan --out=plan_dev.yml
      - terraform apply plan_dev.yml
      - terraform destroy --auto-approve
      