version: 0.2

env:
  parameter-store:
    tf_vars_location: /dev/tf_vars_location

phases:
  install:
    commands:
      - cd dev
      - aws s3 cp $tf_vars_location dev.auto.tfvars
  build:
    commands:
      - terraform validate 
      - terraform init
      - terraform plan --out=plan_dev.yml
      - terraform apply plan_dev.yml --auto-approve
      - terraform destroy --auto-approve
